### ISSUE TITLE
Build failure - Entry name 'classes.dex' collided (Android)

### ISSUE THREAD

**Issue by chrislaurie-io** [FlorisDevreese/Flutter-CI-CD#2]

**Comment by chrislaurie-bs** [comment]
And my pipeline is simple - this has worked sereval time, until I added device_info_plus: 

name: $(Date:yyyyMMdd)$(Rev:r)
trigger:
- main

pool:
  vmImage: windows-latest

jobs:
  - job: BuildAndroid
    displayName: Build for Android
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'latest'
    - task: FlutterBuild@0
      inputs:
        target: 'apk'
        projectDirectory: '.'
        additionalArguments: '--dart-define=MYFABORY_APP_NAME=MyFaboryD --dart-define=MYFABORY_APP_SUFFIX=.dev'
    - task: PublishBuildArtifacts@1
      displayName: Publish artifact
      inputs:
        PathtoPublish: '$(Build.Repository.LocalPath)/build/app/outputs/apk/release'
        ArtifactName: 'apk'
        publishLocation: 'Container'
